// components/TermsAndConditions.jsx
import React from "react";

export default function TermsAndConditions() {
  return (
    <section className="bg-[#FAFAF0] text-[#1C1C1C] py-16 px-6 md:px-20 mt-1">
      <div className="max-w-5xl mx-auto space-y-10">
        <h1 className="text-4xl font-bold text-red-700 border-b-2 border-red-600 pb-2">
          Terms & Conditions
        </h1>

        <p className="text-sm text-gray-700">
          This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
        </p>

        <p className="text-sm text-gray-700">
          This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of domain name <strong className="text-red-600">https://drishtiboutiquecollection.com/</strong> ('Website'), including the related mobile site and mobile application (collectively referred to as the 'Platform').
        </p>

        <p className="text-sm text-gray-700">
          The Platform is owned by <strong className="text-red-700">Drishti Boutique Collection</strong>, Garden-110059, a company incorporated under the Companies Act, 1956 with its registered office at Near By Satya Hospital, Pipal Road, Mohan (hereinafter referred to as ‘Platform Owner’, 'we', 'us', 'our').
        </p>

        <div className="space-y-6">
          <h2 className="text-2xl font-semibold text-red-700">General Use</h2>

          <ul className="list-decimal list-inside space-y-2 text-gray-800">
            <li>
              ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE. PLEASE READ CAREFULLY BEFORE PROCEEDING.
            </li>
            <li>
              By using the Platform, you agree to provide accurate and complete information and are responsible for all activities under your registered account.
            </li>
            <li>
              Use of the Platform and Services is at your own risk. We do not guarantee the accuracy, completeness, or performance of any content or services.
            </li>
            <li>
              The Platform and its content are proprietary and protected. You may not use or claim any ownership over the content, design, or layout.
            </li>
            <li>
              Unauthorized use may result in legal action under applicable laws.
            </li>
            <li>
              All fees associated with Services are to be paid as required.
            </li>
            <li>
              Use of the Platform must be lawful and in accordance with these Terms and local laws.
            </li>
            <li>
              Third-party links on the Platform are for convenience only; we are not responsible for their content or policies.
            </li>
            <li>
              Initiating a transaction means entering a legally binding agreement with the Platform Owner.
            </li>
            <li>
              You agree to indemnify and hold harmless Drishti Boutique Collection, its officers, employees, and affiliates from any legal claims, fees, or damages arising from your use of the Platform.
            </li>
            <li>
              We are not liable for delays or failures caused by force majeure events.
            </li>
            <li>
              These Terms are governed by the laws of India.
            </li>
            <li>
              Any disputes shall be under the exclusive jurisdiction of the courts in New Delhi and Delhi.
            </li>
            <li>
              For any concerns, you may reach us using the contact information provided on this website.
            </li>
          </ul>
        </div>
      </div>
    </section>
  );
}
